# Generated by Django 4.0.4 on 2022-05-31 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0002_quiz_multiple_quiz_true_false_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiple',
            old_name='response',
            new_name='correct',
        ),
        migrations.RenameField(
            model_name='true_false',
            old_name='response',
            new_name='correct',
        ),
    ]
